---
- name: Install Fail2Ban
  ansible.builtin.package:
    name: fail2ban
  notify: Restart SSH

- name: Config fail2ban
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Start and autostart Fail2Ban
