---
hostname: scorpion-hostvds

base_packages_list:
  - sudo
  - micro
  - curl
  - git
  - thefuck
  - zoxide
  - trash-cli
  - direnv
  - fish
  - zstd
  - keychain
  - ufw

user_setup_name: "{{ scorpion_user.name }}"
user_setup_shell: "{{ scorpion_user.shell }}"
user_setup_groups: "{{ scorpion_user.groups }}"
shell_fish_user: "{{ scorpion_user.name }}"

pay_respects_user: "{{ scorpion_user.name }}"
pay_respects_shell: "{{ scorpion_user.shell }}"

ssh_client_user: "{{ scorpion_user.name }}"
ssh_client_vds_host: "{{ vds.host }}"
ssh_client_vds_user: "{{ scorpion_user.name }}"
ssh_client_vds_identity_file: "{{ vds.identity_file }}"

sshd_disable_password_auth: true
sshd_disable_include_conf: true

ufw_default_incoming: deny
ufw_default_outgoing: allow
ufw_logging: low
ufw_rules:
  - { rule: limit, name: "OpenSSH" } # delete: true to delete rule
  - { rule: allow, port: "80", proto: tcp }
  - { rule: allow, port: "443", proto: tcp }
