---
hostname: scorpion-hostvds

base_packages_list:
  - sudo
  - micro
  - less
  - curl
  - git
  - thefuck
  - zoxide
  - trash-cli
  - direnv
  - fish
  - zstd
  - keychain
  - ufw
  - fail2ban

sshd_disable_password_auth: true
sshd_disable_include_conf: true
sshd_service_name: ssh

fail2ban_sshd_service_name: ssh
fail2ban_banaction_ufw: true

ufw_default_incoming: deny
ufw_default_outgoing: allow
ufw_logging: low
ufw_rules:
  - { rule: limit, name: "OpenSSH" } # delete: true to delete rule
  - { rule: allow, port: "80", proto: tcp }
  - { rule: allow, port: "443", proto: tcp }

docker_users: []
docker_add_repo: true
