---
hostname: wsl

base_packages_list:
  - sudo
  - micro
  - less
  - base-devel
  - openssh
  - keychain
  - thefuck
  - zoxide
  - trash-cli
  - direnv
  - uv
  - fish

user_setup_name: "{{ scorpion_user.name }}"
user_setup_shell: "{{ scorpion_user.shell }}"

shell_fish_user: "{{ scorpion_user.name }}"

ssh_client_user: "{{ scorpion_user.name }}"
ssh_client_vds_host: "{{ vds.host }}"
ssh_client_vds_user: "{{ scorpion_user.name }}"
ssh_client_vds_identity_file: "{{ vds.identity_file }}"
