---
base_packages_list:
  - sudo
  - micro
  - less
  - curl
  - git
  - openssh
  - keychain
  - thefuck
  - zoxide
  - trash-cli
  - direnv
  - uv
  - fish

user_setup_groups: []
ssh_client_copy_local: true
